export const TZ_TO_WTIMES: Record<string, { cc: string; city: string }> = {
	"Asia/Mecca": { cc: "SA", city: "MAKKAH" },
	"Asia/Riyadh": { cc: "SA", city: "RIYADH" },
	"Asia/Dubai": { cc: "AE", city: "DUBAI" },
	"Asia/Kuwait": { cc: "KW", city: "KUWAIT" },
	"Asia/Qatar": { cc: "QA", city: "DOHA" },
	"Asia/Bahrain": { cc: "BH", city: "MANAMA" },
	"Asia/Muscat": { cc: "OM", city: "MUSCAT" },
	"Asia/Baghdad": { cc: "IQ", city: "BAGHDAD" },
	"Asia/Damascus": { cc: "SY", city: "DAMASCUS" },
	"Asia/Beirut": { cc: "LB", city: "BEIRUT" },
	"Asia/Amman": { cc: "JO", city: "AMMAN" },
	"Asia/Jerusalem": { cc: "PS", city: "JERUSALEM" },
	"Africa/Cairo": { cc: "EG", city: "CAIRO" },
	"Africa/Casablanca": { cc: "MA", city: "CASABLANCA" },
	"Africa/Tunis": { cc: "TN", city: "TUNIS" },
	"Africa/Algiers": { cc: "DZ", city: "ALGIERS" },
	"Europe/Istanbul": { cc: "TR", city: "ISTANBUL" },
	"Asia/Karachi": { cc: "PK", city: "KARACHI" },
	"Asia/Dhaka": { cc: "BD", city: "DHAKA" },
	"Asia/Jakarta": { cc: "ID", city: "JAKARTA" },
	"Asia/Kuala_Lumpur": { cc: "MY", city: "KUALA_LUMPUR" },
	"Europe/London": { cc: "UK", city: "LONDON" },
	"America/New_York": { cc: "US", city: "NEW_YORK" },
	"America/Los_Angeles": { cc: "US", city: "LOS_ANGELES" },
	"America/Toronto": { cc: "CA", city: "TORONTO" },
	"Australia/Sydney": { cc: "AU", city: "SYDNEY" },
};
